<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <Choose>
        <When Condition="$(Configuration)=='Release'">
            <PropertyGroup>
                <DebugSymbols>false</DebugSymbols>
                <Optimize>true</Optimize>
                <DefineConstants>TRACE</DefineConstants>
            </PropertyGroup>
        </When>

        <When Condition="$(Configuration)=='Debug'">
            <Choose>
                <When Condition="$([MSBuild]::IsOSPlatform('Windows'))">
                    <PropertyGroup>
                    </PropertyGroup>
                </When>
                <When Condition="$([MSBuild]::IsOSPlatform('OSX'))">
                    <PropertyGroup>
                    </PropertyGroup>
                </When>
                <When Condition="$([MSBuild]::IsOSPlatform('Linux'))">
                    <PropertyGroup>
                    </PropertyGroup>
                </When>
            </Choose>
        </When>

    </Choose>
    
  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="4.3.3.952" />
    <PackageReference Include="NLog" Version="5.2.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SystemModule\SystemModule.csproj" />
  </ItemGroup>
  
</Project>
