//! 由 `script-tool gen-codes` 从 C# 参照源码机械生成，请勿手改。
//! 数据源: src/Modules/ScriptEngine/Consts/{ConditionCode,ExecutionCode,GrobalVarCode}.cs
//! 重跑: cargo run -p mir2-script-tool -- gen-codes

/// 脚本命令码定义：命令名 → (GetFields 字段序号, 枚举值)。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CodeDef {
    /// ScriptDefName 命令名
    pub name: &'static str,
    /// 枚举成员名
    pub member: &'static str,
    /// typeof(X).GetFields() 字段序号（value__ 占 0 号位）
    pub field_index: i32,
    /// 枚举数值
    pub enum_value: i32,
}

/// CONDITION_CODES（207 条）
#[rustfmt::skip]
pub static CONDITION_CODES: &[CodeDef] = &[
    CodeDef { name: "CHECK", member: "CHECK", field_index: 1, enum_value: 1 },
    CodeDef { name: "RANDOM", member: "RANDOM", field_index: 2, enum_value: 2 },
    CodeDef { name: "GENDER", member: "GENDER", field_index: 3, enum_value: 3 },
    CodeDef { name: "DAYTIME", member: "DAYTIME", field_index: 4, enum_value: 4 },
    CodeDef { name: "CHECKOPEN", member: "CHECKOPEN", field_index: 5, enum_value: 5 },
    CodeDef { name: "CHECKUNIT", member: "CHECKUNIT", field_index: 6, enum_value: 6 },
    CodeDef { name: "CHECKLEVEL", member: "CHECKLEVEL", field_index: 7, enum_value: 7 },
    CodeDef { name: "CHECKJOB", member: "CHECKJOB", field_index: 8, enum_value: 8 },
    CodeDef { name: "CHECKBBCOUNT", member: "CHECKBBCOUNT", field_index: 9, enum_value: 9 },
    CodeDef { name: "CHECKITEM", member: "CHECKITEM", field_index: 10, enum_value: 10 },
    CodeDef { name: "CHECKITEMW", member: "CHECKITEMW", field_index: 11, enum_value: 11 },
    CodeDef { name: "CHECKGOLD", member: "CHECKGOLD", field_index: 12, enum_value: 12 },
    CodeDef { name: "ISTAKEITEM", member: "ISTAKEITEM", field_index: 13, enum_value: 13 },
    CodeDef { name: "CHECKDURA", member: "CHECKDURA", field_index: 14, enum_value: 14 },
    CodeDef { name: "CHECKDURAEVA", member: "CHECKDURAEVA", field_index: 15, enum_value: 15 },
    CodeDef { name: "DAYOFWEEK", member: "DAYOFWEEK", field_index: 16, enum_value: 16 },
    CodeDef { name: "HOUR", member: "HOUR", field_index: 17, enum_value: 17 },
    CodeDef { name: "MIN", member: "MIN", field_index: 18, enum_value: 18 },
    CodeDef { name: "CHECKPKPOINT", member: "CHECKPKPOINT", field_index: 19, enum_value: 19 },
    CodeDef { name: "CHECKLUCKYPOINT", member: "CHECKLUCKYPOINT", field_index: 20, enum_value: 20 },
    CodeDef { name: "CHECKMONMAP", member: "CHECKMONMAP", field_index: 21, enum_value: 21 },
    CodeDef { name: "CHECKMONAREA", member: "CHECKMONAREA", field_index: 22, enum_value: 22 },
    CodeDef { name: "CHECKHUM", member: "CHECKHUM", field_index: 23, enum_value: 23 },
    CodeDef { name: "CHECKBAGGAGE", member: "CHECKBAGGAGE", field_index: 24, enum_value: 24 },
    CodeDef { name: "EQUAL", member: "EQUAL", field_index: 25, enum_value: 25 },
    CodeDef { name: "LARGE", member: "LARGE", field_index: 26, enum_value: 26 },
    CodeDef { name: "SMALL", member: "SMALL", field_index: 27, enum_value: 27 },
    CodeDef { name: "CHECKMAGIC", member: "CHECKMAGIC", field_index: 28, enum_value: 28 },
    CodeDef { name: "CHKMAGICLEVEL", member: "CHKMAGICLEVEL", field_index: 29, enum_value: 29 },
    CodeDef { name: "CHECKMONRECALL", member: "CHECKMONRECALL", field_index: 30, enum_value: 30 },
    CodeDef { name: "CHECKHORSE", member: "CHECKHORSE", field_index: 31, enum_value: 31 },
    CodeDef { name: "CHECKRIDING", member: "CHECKRIDING", field_index: 32, enum_value: 32 },
    CodeDef { name: "STARTDAILYQUEST", member: "STARTDAILYQUEST", field_index: 33, enum_value: 33 },
    CodeDef { name: "CHECKDAILYQUEST", member: "CHECKDAILYQUEST", field_index: 34, enum_value: 34 },
    CodeDef { name: "RANDOMEX", member: "RANDOMEX", field_index: 35, enum_value: 35 },
    CodeDef { name: "CHECKNAMELIST", member: "CHECKNAMELIST", field_index: 36, enum_value: 36 },
    CodeDef { name: "CHECKWEAPONLEVEL", member: "CHECKWEAPONLEVEL", field_index: 37, enum_value: 37 },
    CodeDef { name: "CHECKWEAPONATOM", member: "CHECKWEAPONATOM", field_index: 38, enum_value: 38 },
    CodeDef { name: "CHECKREFINEWEAPON", member: "CHECKREFINEWEAPON", field_index: 39, enum_value: 39 },
    CodeDef { name: "CHECKWEAPONMCTYPE", member: "CHECKWEAPONMCTYPE", field_index: 40, enum_value: 40 },
    CodeDef { name: "CHECKREFINEITEM", member: "CHECKREFINEITEM", field_index: 41, enum_value: 41 },
    CodeDef { name: "HASWEAPONATOM", member: "HASWEAPONATOM", field_index: 42, enum_value: 42 },
    CodeDef { name: "ISGUILDMASTER", member: "ISGUILDMASTER", field_index: 43, enum_value: 43 },
    CodeDef { name: "CANPROPOSECASTLEWAR", member: "CANPROPOSECASTLEWAR", field_index: 44, enum_value: 44 },
    CodeDef { name: "CANHAVESHOOTER", member: "CANHAVESHOOTER", field_index: 45, enum_value: 45 },
    CodeDef { name: "CHECKFAME", member: "CHECKFAME", field_index: 46, enum_value: 46 },
    CodeDef { name: "ISONCASTLEWAR", member: "ISONCASTLEWAR", field_index: 47, enum_value: 47 },
    CodeDef { name: "ISONREADYCASTLEWAR", member: "ISONREADYCASTLEWAR", field_index: 48, enum_value: 48 },
    CodeDef { name: "ISCASTLEGUILD", member: "ISCASTLEGUILD", field_index: 49, enum_value: 49 },
    CodeDef { name: "ISATTACKGUILD", member: "ISATTACKGUILD", field_index: 50, enum_value: 50 },
    CodeDef { name: "ISDEFENSEGUILD", member: "ISDEFENSEGUILD", field_index: 51, enum_value: 51 },
    CodeDef { name: "CHECKSHOOTER", member: "CHECKSHOOTER", field_index: 52, enum_value: 52 },
    CodeDef { name: "CHECKSAVEDSHOOTER", member: "CHECKSAVEDSHOOTER", field_index: 53, enum_value: 53 },
    CodeDef { name: "HAVEGUILD", member: "HASGUILD", field_index: 54, enum_value: 54 },
    CodeDef { name: "CHECKCASTLEDOOR", member: "CHECKCASTLEDOOR", field_index: 55, enum_value: 55 },
    CodeDef { name: "CHECKCASTLEDOOROPEN", member: "CHECKCASTLEDOOROPEN", field_index: 56, enum_value: 56 },
    CodeDef { name: "CHECKPOS", member: "CHECKPOS", field_index: 57, enum_value: 57 },
    CodeDef { name: "CANCHARGESHOOTER", member: "CANCHARGESHOOTER", field_index: 58, enum_value: 58 },
    CodeDef { name: "ISATTACKALLYGUILD", member: "ISATTACKALLYGUILD", field_index: 59, enum_value: 59 },
    CodeDef { name: "ISDEFENSEALLYGUILD", member: "ISDEFENSEALLYGUILD", field_index: 60, enum_value: 60 },
    CodeDef { name: "TESTTEAM", member: "TESTTEAM", field_index: 61, enum_value: 61 },
    CodeDef { name: "ISSYSOP", member: "ISSYSOP", field_index: 62, enum_value: 62 },
    CodeDef { name: "ISADMIN", member: "ISADMIN", field_index: 63, enum_value: 63 },
    CodeDef { name: "CHECKBONUS", member: "CHECKBONUS", field_index: 64, enum_value: 64 },
    CodeDef { name: "CHECKMARRIAGE", member: "CHECKMARRIAGE", field_index: 65, enum_value: 65 },
    CodeDef { name: "CHECKMARRIAGERING", member: "CHECKMARRIAGERING", field_index: 66, enum_value: 66 },
    CodeDef { name: "CHECKGMETERM", member: "CHECKGMETERM", field_index: 67, enum_value: 67 },
    CodeDef { name: "CHECKOPENGME", member: "CHECKOPENGME", field_index: 68, enum_value: 68 },
    CodeDef { name: "CHECKENTERGMEMAP", member: "CHECKENTERGMEMAP", field_index: 69, enum_value: 69 },
    CodeDef { name: "CHECKSERVER", member: "CHECKSERVER", field_index: 70, enum_value: 70 },
    CodeDef { name: "ELARGE", member: "ELARGE", field_index: 71, enum_value: 71 },
    CodeDef { name: "ESMALL", member: "ESMALL", field_index: 72, enum_value: 72 },
    CodeDef { name: "CHECKGROUPCOUNT", member: "CHECKGROUPCOUNT", field_index: 73, enum_value: 73 },
    CodeDef { name: "CHECKACCESSORY", member: "CHECKACCESSORY", field_index: 74, enum_value: 74 },
    CodeDef { name: "ONERROR", member: "ONERROR", field_index: 75, enum_value: 75 },
    CodeDef { name: "CHECKARMOR", member: "CHECKARMOR", field_index: 76, enum_value: 76 },
    CodeDef { name: "CHECKACCOUNTLIST", member: "CHECKACCOUNTLIST", field_index: 77, enum_value: 77 },
    CodeDef { name: "CHECKIPLIST", member: "CHECKIPLIST", field_index: 78, enum_value: 78 },
    CodeDef { name: "CHECKCREDITPOINT", member: "CHECKCREDITPOINT", field_index: 79, enum_value: 79 },
    CodeDef { name: "CHECKPOSEDIR", member: "CHECKPOSEDIR", field_index: 80, enum_value: 80 },
    CodeDef { name: "CHECKPOSELEVEL", member: "CHECKPOSELEVEL", field_index: 81, enum_value: 81 },
    CodeDef { name: "CHECKPOSEGENDER", member: "CHECKPOSEGENDER", field_index: 82, enum_value: 82 },
    CodeDef { name: "CHECKLEVELEX", member: "CHECKLEVELEX", field_index: 83, enum_value: 83 },
    CodeDef { name: "CHECKBONUSPOINT", member: "CHECKBONUSPOINT", field_index: 84, enum_value: 84 },
    CodeDef { name: "CHECKMARRY", member: "CHECKMARRY", field_index: 85, enum_value: 85 },
    CodeDef { name: "CHECKPOSEMARRY", member: "CHECKPOSEMARRY", field_index: 86, enum_value: 86 },
    CodeDef { name: "CHECKMARRYCOUNT", member: "CHECKMARRYCOUNT", field_index: 87, enum_value: 87 },
    CodeDef { name: "CHECKMASTER", member: "CHECKMASTER", field_index: 88, enum_value: 88 },
    CodeDef { name: "HAVEMASTER", member: "HAVEMASTER", field_index: 89, enum_value: 89 },
    CodeDef { name: "CHECKPOSEMASTER", member: "CHECKPOSEMASTER", field_index: 90, enum_value: 90 },
    CodeDef { name: "POSEHAVEMASTER", member: "POSEHAVEMASTER", field_index: 91, enum_value: 91 },
    CodeDef { name: "CHECKPOSEISMASTER", member: "CHECKISMASTER", field_index: 92, enum_value: 92 },
    CodeDef { name: "CHECKISMASTER", member: "CHECKPOSEISMASTER", field_index: 93, enum_value: 93 },
    CodeDef { name: "CHECKNAMEIPLIST", member: "CHECKNAMEIPLIST", field_index: 94, enum_value: 94 },
    CodeDef { name: "CHECKACCOUNTIPLIST", member: "CHECKACCOUNTIPLIST", field_index: 95, enum_value: 95 },
    CodeDef { name: "CHECKSLAVECOUNT", member: "CHECKSLAVECOUNT", field_index: 96, enum_value: 96 },
    CodeDef { name: "ISCASTLEMASTER", member: "CHECKCASTLEMASTER", field_index: 97, enum_value: 97 },
    CodeDef { name: "ISNEWHUMAN", member: "ISNEWHUMAN", field_index: 98, enum_value: 98 },
    CodeDef { name: "CHECKMEMBERTYPE", member: "CHECKMEMBERTYPE", field_index: 99, enum_value: 99 },
    CodeDef { name: "CHECKMEMBERLEVEL", member: "CHECKMEMBERLEVEL", field_index: 100, enum_value: 100 },
    CodeDef { name: "CHECKGAMEGOLD", member: "CHECKGAMEGOLD", field_index: 101, enum_value: 101 },
    CodeDef { name: "CHECKGAMEPOINT", member: "CHECKGAMEPOINT", field_index: 102, enum_value: 102 },
    CodeDef { name: "CHECKNAMELISTPOSITION", member: "CHECKNAMELISTPOSITION", field_index: 103, enum_value: 103 },
    CodeDef { name: "CHECKGUILDLIST", member: "CHECKGUILDLIST", field_index: 104, enum_value: 104 },
    CodeDef { name: "CHECKRENEWLEVEL", member: "CHECKRENEWLEVEL", field_index: 105, enum_value: 105 },
    CodeDef { name: "CHECKSLAVELEVEL", member: "CHECKSLAVELEVEL", field_index: 106, enum_value: 106 },
    CodeDef { name: "CHECKSLAVENAME", member: "CHECKSLAVENAME", field_index: 107, enum_value: 107 },
    CodeDef { name: "CHECKOFGUILD", member: "CHECKOFGUILD", field_index: 108, enum_value: 108 },
    CodeDef { name: "CHECKPAYMENT", member: "CHECKPAYMENT", field_index: 109, enum_value: 109 },
    CodeDef { name: "CHECKUSEITEM", member: "CHECKUSEITEM", field_index: 110, enum_value: 110 },
    CodeDef { name: "CHECKBAGSIZE", member: "CHECKBAGSIZE", field_index: 111, enum_value: 111 },
    CodeDef { name: "CHECKLISTCOUNT", member: "CHECKLISTCOUNT", field_index: 112, enum_value: 112 },
    CodeDef { name: "CHECKDC", member: "CHECKDC", field_index: 113, enum_value: 113 },
    CodeDef { name: "CHECKMC", member: "CHECKMC", field_index: 114, enum_value: 114 },
    CodeDef { name: "CHECKSC", member: "CHECKSC", field_index: 115, enum_value: 115 },
    CodeDef { name: "CHECKHP", member: "CHECKHP", field_index: 116, enum_value: 116 },
    CodeDef { name: "CHECKMP", member: "CHECKMP", field_index: 117, enum_value: 117 },
    CodeDef { name: "CHECKITEMTYPE", member: "CHECKITEMTYPE", field_index: 118, enum_value: 118 },
    CodeDef { name: "CHECKEXP", member: "CHECKEXP", field_index: 119, enum_value: 119 },
    CodeDef { name: "CHECKCASTLEGOLD", member: "CHECKCASTLEGOLD", field_index: 120, enum_value: 120 },
    CodeDef { name: "PASSWORDERRORCOUNT", member: "PASSWORDERRORCOUNT", field_index: 121, enum_value: 121 },
    CodeDef { name: "ISLOCKPASSWORD", member: "ISLOCKPASSWORD", field_index: 122, enum_value: 122 },
    CodeDef { name: "ISLOCKSTORAGE", member: "ISLOCKSTORAGE", field_index: 123, enum_value: 123 },
    CodeDef { name: "CHECKGUILDBUILDPOINT", member: "CHECKBUILDPOINT", field_index: 124, enum_value: 124 },
    CodeDef { name: "CHECKGUILDAURAEPOINT", member: "CHECKAURAEPOINT", field_index: 125, enum_value: 125 },
    CodeDef { name: "CHECKGUILDSTABILITYPOINT", member: "CHECKSTABILITYPOINT", field_index: 126, enum_value: 126 },
    CodeDef { name: "CHECKGUILDFLOURISHPOINT", member: "CHECKFLOURISHPOINT", field_index: 127, enum_value: 127 },
    CodeDef { name: "CHECKCONTRIBUTION", member: "CHECKCONTRIBUTION", field_index: 128, enum_value: 128 },
    CodeDef { name: "CHECKRANGEMONCOUNT", member: "CHECKRANGEMONCOUNT", field_index: 129, enum_value: 129 },
    CodeDef { name: "CHECKITEMADDVALUE", member: "CHECKITEMADDVALUE", field_index: 130, enum_value: 130 },
    CodeDef { name: "CHECKINMAPRANGE", member: "CHECKINMAPRANGE", field_index: 131, enum_value: 131 },
    CodeDef { name: "CASTLECHANGEDAY", member: "CASTLECHANGEDAY", field_index: 132, enum_value: 132 },
    CodeDef { name: "CASTLEWARAY", member: "CASTLEWARDAY", field_index: 133, enum_value: 133 },
    CodeDef { name: "ONLINELONGMIN", member: "ONLINELONGMIN", field_index: 134, enum_value: 134 },
    CodeDef { name: "CHECKGUILDCHIEFITEMCOUNT", member: "CHECKGUILDCHIEFITEMCOUNT", field_index: 135, enum_value: 135 },
    CodeDef { name: "CHECKNAMEDATELIST", member: "CHECKNAMEDATELIST", field_index: 136, enum_value: 136 },
    CodeDef { name: "CHECKMAPHUMANCOUNT", member: "CHECKMAPHUMANCOUNT", field_index: 137, enum_value: 137 },
    CodeDef { name: "CHECKMAPMONCOUNT", member: "CHECKMAPMONCOUNT", field_index: 138, enum_value: 138 },
    CodeDef { name: "CHECKVAR", member: "CHECKVAR", field_index: 139, enum_value: 139 },
    CodeDef { name: "CHECKSERVERNAME", member: "CHECKSERVERNAME", field_index: 140, enum_value: 140 },
    CodeDef { name: "CHECKMAPNAME", member: "CHECKMAPNAME", field_index: 141, enum_value: 141 },
    CodeDef { name: "INSAFEZONE", member: "INSAFEZONE", field_index: 142, enum_value: 142 },
    CodeDef { name: "CHECKSKILL", member: "CHECKSKILL", field_index: 143, enum_value: 143 },
    CodeDef { name: "CHECKUSERDATE", member: "CHECKUSERDATE", field_index: 144, enum_value: 144 },
    CodeDef { name: "CHECKCONTAINSTEXT", member: "CHECKCONTAINSTEXT", field_index: 145, enum_value: 145 },
    CodeDef { name: "COMPARETEXT", member: "COMPARETEXT", field_index: 146, enum_value: 146 },
    CodeDef { name: "CHECKTEXTLIST", member: "CHECKTEXTLIST", field_index: 147, enum_value: 147 },
    CodeDef { name: "ISGROUPMASTER", member: "ISGROUPMASTER", field_index: 148, enum_value: 148 },
    CodeDef { name: "CHECKCONTAINSTEXTLIST", member: "CHECKCONTAINSTEXTLIST", field_index: 149, enum_value: 149 },
    CodeDef { name: "CHECKONLINE", member: "CHECKONLINE", field_index: 150, enum_value: 150 },
    CodeDef { name: "CHECKTEXTLENGTH", member: "CHECKTEXTLENGTH", field_index: 151, enum_value: 151 },
    CodeDef { name: "ISDUPMODE", member: "ISDUPMODE", field_index: 152, enum_value: 152 },
    CodeDef { name: "ISOFFLINEMODE", member: "ISOFFLINEMODE", field_index: 153, enum_value: 153 },
    CodeDef { name: "CHECKSTATIONTIME", member: "CHECKSTATIONTIME", field_index: 154, enum_value: 154 },
    CodeDef { name: "CHECKSIGNMAP", member: "CHECKSIGNMAP", field_index: 155, enum_value: 155 },
    CodeDef { name: "CHECKGUILDMEMBERMAXLIMIT", member: "CHECKGUILDMEMBERMAXLIMIT", field_index: 156, enum_value: 156 },
    CodeDef { name: "CHECKGUILDNAMEDATELIST", member: "CHECKGUILDNAMEDATELIST", field_index: 157, enum_value: 157 },
    CodeDef { name: "CHECKRANGEROUPCOUNT", member: "CHECKRANGEROUPCOUNT", field_index: 158, enum_value: 158 },
    CodeDef { name: "CHECKONLINEPLAYCOUNT", member: "CHECKONLINEPLAYCOUNT", field_index: 159, enum_value: 159 },
    CodeDef { name: "CHECKITEMLIMIT", member: "CHECKITEMLIMIT", field_index: 160, enum_value: 160 },
    CodeDef { name: "CHECKITEMLIMITCOUNT", member: "CHECKITEMLIMITCOUNT", field_index: 161, enum_value: 161 },
    CodeDef { name: "CHECKMEMORYITEM", member: "CHECKMEMORYITEM", field_index: 162, enum_value: 162 },
    CodeDef { name: "CHECKUPGRADEITEMS", member: "CHECKUPGRADEITEMS", field_index: 163, enum_value: 163 },
    CodeDef { name: "CHECKIPUTTEM", member: "CHECKIPUTTEM", field_index: 164, enum_value: 164 },
    CodeDef { name: "CHECKDEATH", member: "CHECKDEATH", field_index: 165, enum_value: 165 },
    CodeDef { name: "ISUNDERWAR", member: "ISUNDERWAR", field_index: 166, enum_value: 166 },
    CodeDef { name: "CHECKPKPOINTEX", member: "CHECKPKPOINTEX", field_index: 167, enum_value: 167 },
    CodeDef { name: "CHECKUSEITEMBIND", member: "CHECKUSEITEMBIND", field_index: 168, enum_value: 168 },
    CodeDef { name: "CHECKITEMBIND", member: "CHECKITEMBIND", field_index: 169, enum_value: 169 },
    CodeDef { name: "CHECKITEMNEWADDVALUE", member: "CHECKITEMNEWADDVALUE", field_index: 170, enum_value: 170 },
    CodeDef { name: "ISSPACELOCK", member: "ISSPACELOCK", field_index: 171, enum_value: 171 },
    CodeDef { name: "CHECKRANGEMAPMAGICEVENTCOUNT", member: "CHECKRANGEMAPMAGICEVENTCOUNT", field_index: 172, enum_value: 172 },
    CodeDef { name: "CHECKITEMNEWADDVALUECOUNT", member: "CHECKITEMNEWADDVALUECOUNT", field_index: 173, enum_value: 173 },
    CodeDef { name: "GETDUELMAP", member: "GETDUELMAP", field_index: 174, enum_value: 174 },
    CodeDef { name: "CHECKMAPDUELING", member: "CHECKMAPDUELING", field_index: 175, enum_value: 175 },
    CodeDef { name: "CHECKHUMDUELING", member: "CHECKHUMDUELING", field_index: 176, enum_value: 176 },
    CodeDef { name: "CHECKCANUSEITEM", member: "CHECKCANUSEITEM", field_index: 177, enum_value: 177 },
    CodeDef { name: "CHECKINCURRRECT", member: "CHECKINCURRRECT", field_index: 178, enum_value: 178 },
    CodeDef { name: "CHECKGUILDMEMBER", member: "CHECKGUILDMEMBER", field_index: 179, enum_value: 179 },
    CodeDef { name: "INDEXOF", member: "INDEXOF", field_index: 180, enum_value: 180 },
    CodeDef { name: "CHECKMASKED", member: "CHECKMASKED", field_index: 181, enum_value: 181 },
    CodeDef { name: "CHECKUSEITEMSTARSLEVEL", member: "CHECKUSEITEMSTARSLEVEL", field_index: 182, enum_value: 182 },
    CodeDef { name: "CHECKBAGITEMSTARSLEVEL", member: "CHECKBAGITEMSTARSLEVEL", field_index: 183, enum_value: 183 },
    CodeDef { name: "CHECKHEROGROUP", member: "CHECKHEROGROUP", field_index: 184, enum_value: 184 },
    CodeDef { name: "CHECKPUTITEMTYPE", member: "CHECKPUTITEMTYPE", field_index: 185, enum_value: 185 },
    CodeDef { name: "CHECKSLAVERANGE", member: "CHECKSLAVERANGE", field_index: 186, enum_value: 186 },
    CodeDef { name: "ISAI", member: "ISAI", field_index: 187, enum_value: 187 },
    CodeDef { name: "CHECKBAGITEMINLIST", member: "CHECKBAGITEMINLIST", field_index: 188, enum_value: 188 },
    CodeDef { name: "INCASTLEWARAREA", member: "INCASTLEWARAREA", field_index: 189, enum_value: 189 },
    CodeDef { name: "ISONMAP", member: "ISONMAP", field_index: 190, enum_value: 190 },
    CodeDef { name: "CHECKISONMAP", member: "CHECKISONMAP", field_index: 191, enum_value: 191 },
    CodeDef { name: "REVIVESLAVES", member: "REVIVESLAVE", field_index: 192, enum_value: 192 },
    CodeDef { name: "CHECKMAGICLVL", member: "CHECKMAGICLVL", field_index: 193, enum_value: 193 },
    CodeDef { name: "CHECKGROUPCLASS", member: "CHECKGROUPCLASS", field_index: 194, enum_value: 194 },
    CodeDef { name: "ISHIGH", member: "ISHIGH", field_index: 195, enum_value: 195 },
    CodeDef { name: "CHECKDIEMON", member: "CHECKDIEMON", field_index: 196, enum_value: 196 },
    CodeDef { name: "CHECKKILLPLAYMON", member: "CHECKKILLPLAYMON", field_index: 197, enum_value: 197 },
    CodeDef { name: "CHECKRANDOMNO", member: "CHECKRANDOMNO", field_index: 198, enum_value: 198 },
    CodeDef { name: "KILLBYHUM", member: "KILLBYHUM", field_index: 199, enum_value: 199 },
    CodeDef { name: "KILLBYMON", member: "KILLBYMON", field_index: 200, enum_value: 200 },
    CodeDef { name: "CHECKINSAFEZONE", member: "CHECKINSAFEZONE", field_index: 201, enum_value: 201 },
    CodeDef { name: "CHECKDLGITEMADDVALUE", member: "CHECKDLGITEMADDVALUE", field_index: 202, enum_value: 202 },
    CodeDef { name: "CHECKDLGITEMTYPE", member: "CHECKDLGITEMTYPE", field_index: 203, enum_value: 203 },
    CodeDef { name: "CHECKDLGITEMNAME", member: "CHECKDLGITEMNAME", field_index: 204, enum_value: 204 },
    CodeDef { name: "CHECKDEATHPLAYMON", member: "SCHECKDEATHPLAYMON", field_index: 205, enum_value: 205 },
    CodeDef { name: "CHECKKILLMONNAME", member: "CHECKKILLMONNAME", field_index: 206, enum_value: 206 },
    CodeDef { name: "CHECKMAP", member: "CHECKMAP", field_index: 207, enum_value: 207 },
];

/// EXECUTION_CODES（352 条）
#[rustfmt::skip]
pub static EXECUTION_CODES: &[CodeDef] = &[
    CodeDef { name: "Set", member: "Set", field_index: 1, enum_value: 1 },
    CodeDef { name: "Take", member: "Take", field_index: 2, enum_value: 2 },
    CodeDef { name: "GIVE", member: "Give", field_index: 3, enum_value: 3 },
    CodeDef { name: "TAKEW", member: "Takew", field_index: 4, enum_value: 4 },
    CodeDef { name: "CLOSE", member: "Close", field_index: 5, enum_value: 5 },
    CodeDef { name: "RESET", member: "ReSet", field_index: 6, enum_value: 6 },
    CodeDef { name: "SETOPEN", member: "SetOpen", field_index: 7, enum_value: 7 },
    CodeDef { name: "SETUNIT", member: "SetUnit", field_index: 8, enum_value: 8 },
    CodeDef { name: "RESETUNIT", member: "ResetUnit", field_index: 9, enum_value: 9 },
    CodeDef { name: "BREAK", member: "Break", field_index: 10, enum_value: 10 },
    CodeDef { name: "TIMERECALL", member: "TimereCall", field_index: 11, enum_value: 11 },
    CodeDef { name: "PARAM1", member: "Param1", field_index: 12, enum_value: 12 },
    CodeDef { name: "PARAM2", member: "Param2", field_index: 13, enum_value: 13 },
    CodeDef { name: "PARAM3", member: "Param3", field_index: 14, enum_value: 14 },
    CodeDef { name: "PARAM4", member: "Param4", field_index: 15, enum_value: 15 },
    CodeDef { name: "EXEACTION", member: "Exeaction", field_index: 16, enum_value: 16 },
    CodeDef { name: "MAPMOVE", member: "MapMove", field_index: 17, enum_value: 17 },
    CodeDef { name: "MAP", member: "Map", field_index: 18, enum_value: 18 },
    CodeDef { name: "TAKECHECKITEM", member: "TakecheckItem", field_index: 19, enum_value: 19 },
    CodeDef { name: "MONGEN", member: "MonGen", field_index: 20, enum_value: 20 },
    CodeDef { name: "MONGENP", member: "MonGenp", field_index: 21, enum_value: 21 },
    CodeDef { name: "MONCLEAR", member: "MonClear", field_index: 22, enum_value: 22 },
    CodeDef { name: "MOV", member: "Mov", field_index: 23, enum_value: 23 },
    CodeDef { name: "INC", member: "Inc", field_index: 24, enum_value: 24 },
    CodeDef { name: "DEC", member: "Dec", field_index: 25, enum_value: 25 },
    CodeDef { name: "SUM", member: "Sum", field_index: 26, enum_value: 26 },
    CodeDef { name: "DIV", member: "Div", field_index: 27, enum_value: 27 },
    CodeDef { name: "MUL", member: "Mul", field_index: 28, enum_value: 28 },
    CodeDef { name: "PERCENT", member: "Percent", field_index: 29, enum_value: 29 },
    CodeDef { name: "BREAKTIMERECALL", member: "BreakTimereCall", field_index: 30, enum_value: 30 },
    CodeDef { name: "SENDMSG", member: "SendMsg", field_index: 31, enum_value: 31 },
    CodeDef { name: "CHANGEMODE", member: "ChangeMode", field_index: 32, enum_value: 32 },
    CodeDef { name: "PKPOINT", member: "PkPoint", field_index: 33, enum_value: 33 },
    CodeDef { name: "CHANGEXP", member: "ChangExp", field_index: 34, enum_value: 34 },
    CodeDef { name: "RECALLMOB", member: "ReCallMob", field_index: 35, enum_value: 35 },
    CodeDef { name: "MOVR", member: "Movr", field_index: 36, enum_value: 36 },
    CodeDef { name: "EXCHANGEMAP", member: "ExchangeMap", field_index: 37, enum_value: 37 },
    CodeDef { name: "RECALLMAP", member: "ReCallMap", field_index: 38, enum_value: 38 },
    CodeDef { name: "ADDBATCH", member: "AddBatch", field_index: 39, enum_value: 39 },
    CodeDef { name: "BATCHDELAY", member: "BatchDelay", field_index: 40, enum_value: 40 },
    CodeDef { name: "BATCHMOVE", member: "BatchMove", field_index: 41, enum_value: 41 },
    CodeDef { name: "PLAYDICE", member: "PlayDice", field_index: 42, enum_value: 42 },
    CodeDef { name: "PASTEMAP", member: "PasteMap", field_index: 43, enum_value: 43 },
    CodeDef { name: "LOADGEN", member: "LoadGen", field_index: 44, enum_value: 44 },
    CodeDef { name: "ADDNAMELIST", member: "AddNameList", field_index: 45, enum_value: 45 },
    CodeDef { name: "DELNAMELIST", member: "DelNameList", field_index: 46, enum_value: 46 },
    CodeDef { name: "ADDGUILDLIST", member: "AddGuildList", field_index: 47, enum_value: 47 },
    CodeDef { name: "DELGUILDLIST", member: "DelGuildList", field_index: 48, enum_value: 48 },
    CodeDef { name: "ADDACCOUNTLIST", member: "AddAccountList", field_index: 49, enum_value: 49 },
    CodeDef { name: "DELACCOUNTLIST", member: "DelAccountList", field_index: 50, enum_value: 50 },
    CodeDef { name: "ADDIPLIST", member: "AddIpList", field_index: 51, enum_value: 51 },
    CodeDef { name: "DELIPLIST", member: "DelIpList", field_index: 52, enum_value: 52 },
    CodeDef { name: "GOQUEST", member: "GoQuest", field_index: 53, enum_value: 53 },
    CodeDef { name: "ENDQUEST", member: "EndQuest", field_index: 54, enum_value: 54 },
    CodeDef { name: "GOTO", member: "Goto", field_index: 55, enum_value: 55 },
    CodeDef { name: "HAIRCOLOR", member: "HairColor", field_index: 56, enum_value: 56 },
    CodeDef { name: "WEARCOLOR", member: "WearColor", field_index: 57, enum_value: 57 },
    CodeDef { name: "HAIRSTYLE", member: "Hairstyle", field_index: 58, enum_value: 58 },
    CodeDef { name: "MONRECALL", member: "MonreCall", field_index: 59, enum_value: 59 },
    CodeDef { name: "HORSECALL", member: "HorseCall", field_index: 60, enum_value: 60 },
    CodeDef { name: "HAIRRNDCOL", member: "Hairrndcol", field_index: 61, enum_value: 61 },
    CodeDef { name: "RANDSETDAILYQUEST", member: "Randsetdailyquest", field_index: 62, enum_value: 62 },
    CodeDef { name: "REFINEWEAPON", member: "RefineWeapon", field_index: 63, enum_value: 63 },
    CodeDef { name: "RECALLGROUPMEMBERS", member: "ReCallgroupMembers", field_index: 64, enum_value: 64 },
    CodeDef { name: "MAPTING", member: "Mapting", field_index: 65, enum_value: 65 },
    CodeDef { name: "WRITEWEAPONNAME", member: "WriteWeaponName", field_index: 66, enum_value: 66 },
    CodeDef { name: "ENABLECMD", member: "EnableCmd", field_index: 67, enum_value: 67 },
    CodeDef { name: "LINEMSG", member: "LineMsg", field_index: 68, enum_value: 68 },
    CodeDef { name: "EVENTMSG", member: "EventMsg", field_index: 69, enum_value: 69 },
    CodeDef { name: "SOUNDMSG", member: "SoundMsg", field_index: 70, enum_value: 70 },
    CodeDef { name: "SETMISSION", member: "SetMission", field_index: 71, enum_value: 71 },
    CodeDef { name: "CLEARMISSION", member: "ClearMission", field_index: 72, enum_value: 72 },
    CodeDef { name: "MONPWR", member: "Monpwr", field_index: 73, enum_value: 73 },
    CodeDef { name: "ENTER_OK", member: "EnterOk", field_index: 74, enum_value: 74 },
    CodeDef { name: "ENTER_FAIL", member: "EnterFail", field_index: 75, enum_value: 75 },
    CodeDef { name: "MONADDITEM", member: "MonAddItem", field_index: 76, enum_value: 76 },
    CodeDef { name: "CHANGEWEATHER", member: "Changeweather", field_index: 77, enum_value: 77 },
    CodeDef { name: "CHANGEWEAPONATOM", member: "ChangeWeaponatom", field_index: 78, enum_value: 78 },
    CodeDef { name: "GETREPAIRCOST", member: "GetrepairCost", field_index: 79, enum_value: 79 },
    CodeDef { name: "KILLHORSE", member: "KillHorse", field_index: 80, enum_value: 80 },
    CodeDef { name: "REPAIRITEM", member: "RepairItem", field_index: 81, enum_value: 81 },
    CodeDef { name: "USEREMERGENCYCLOSE", member: "UseremerGencyClose", field_index: 82, enum_value: 82 },
    CodeDef { name: "BUILDGUILD", member: "BuildGuild", field_index: 83, enum_value: 83 },
    CodeDef { name: "GUILDWAR", member: "Guildwar", field_index: 84, enum_value: 84 },
    CodeDef { name: "CHANGEUSERNAME", member: "ChangeUserName", field_index: 85, enum_value: 85 },
    CodeDef { name: "CHANGEMONLEVEL", member: "ChangemonLevel", field_index: 86, enum_value: 86 },
    CodeDef { name: "DROPITEMMAP", member: "DropItemMap", field_index: 87, enum_value: 87 },
    CodeDef { name: "CLEARITEMMAP", member: "ClearItemMap", field_index: 88, enum_value: 88 },
    CodeDef { name: "PROPOSECASTLEWAR", member: "Proposecastlewar", field_index: 89, enum_value: 89 },
    CodeDef { name: "FINISHCASTLEWAR", member: "Finishcastlewar", field_index: 90, enum_value: 90 },
    CodeDef { name: "MOVENPC", member: "MoveNpc", field_index: 91, enum_value: 91 },
    CodeDef { name: "SPEAK", member: "Speak", field_index: 92, enum_value: 92 },
    CodeDef { name: "SENDCMD", member: "SendCmd", field_index: 93, enum_value: 93 },
    CodeDef { name: "INCFAME", member: "IncFame", field_index: 94, enum_value: 94 },
    CodeDef { name: "DECFAME", member: "DecFame", field_index: 95, enum_value: 95 },
    CodeDef { name: "CAPTURECASTLEFLAG", member: "CapturecastleFlag", field_index: 96, enum_value: 96 },
    CodeDef { name: "MAKESHOOTER", member: "MakeShooter", field_index: 97, enum_value: 97 },
    CodeDef { name: "KILLSHOOTER", member: "KillShooter", field_index: 98, enum_value: 98 },
    CodeDef { name: "LEAVESHOOTER", member: "LeaveShooter", field_index: 99, enum_value: 99 },
    CodeDef { name: "CHANGEMAPATTR", member: "ChangeMapAttr", field_index: 100, enum_value: 100 },
    CodeDef { name: "RESETMAPATTR", member: "ResetMapAttr", field_index: 101, enum_value: 101 },
    CodeDef { name: "MAKECASTLEDOOR", member: "MakeCastleDoor", field_index: 102, enum_value: 102 },
    CodeDef { name: "REPAIRCASTLEDOOR", member: "RepairCastleDoor", field_index: 103, enum_value: 103 },
    CodeDef { name: "CHARGESHOOTER", member: "ChargeShooter", field_index: 104, enum_value: 104 },
    CodeDef { name: "SETAREAATTR", member: "SetareaAttr", field_index: 105, enum_value: 105 },
    CodeDef { name: "TESTFLAG", member: "TestFlag", field_index: 106, enum_value: 106 },
    CodeDef { name: "APPLYFLAG", member: "ApplyFlag", field_index: 107, enum_value: 107 },
    CodeDef { name: "PASTEFLAG", member: "PasteFlag", field_index: 108, enum_value: 108 },
    CodeDef { name: "GETBACKCASTLEGOLD", member: "GetBackCastleGold", field_index: 109, enum_value: 109 },
    CodeDef { name: "GETBACKUPGITEM", member: "GetBackUpgItem", field_index: 110, enum_value: 110 },
    CodeDef { name: "TINGWAR", member: "TingWar", field_index: 111, enum_value: 111 },
    CodeDef { name: "SAVEPASSWD", member: "SavePasswd", field_index: 112, enum_value: 112 },
    CodeDef { name: "CREATENPC", member: "CreateNpc", field_index: 113, enum_value: 113 },
    CodeDef { name: "TAKEBONUS", member: "TakeBonus", field_index: 114, enum_value: 114 },
    CodeDef { name: "SYSMSG", member: "SysMsg", field_index: 115, enum_value: 115 },
    CodeDef { name: "LOADVALUE", member: "LoadValue", field_index: 116, enum_value: 116 },
    CodeDef { name: "SAVEVALUE", member: "SaveValue", field_index: 117, enum_value: 117 },
    CodeDef { name: "SAVELOG", member: "SaveLog", field_index: 118, enum_value: 118 },
    CodeDef { name: "GETMARRIED", member: "GetMarried", field_index: 119, enum_value: 119 },
    CodeDef { name: "DIVORCE", member: "Divorce", field_index: 120, enum_value: 120 },
    CodeDef { name: "CAPTURESAYING", member: "CaptureSaying", field_index: 121, enum_value: 121 },
    CodeDef { name: "CANCELMARRIAGERING", member: "CancelMarriagering", field_index: 122, enum_value: 122 },
    CodeDef { name: "OPENUSERMARKET", member: "OpenUserMarket", field_index: 123, enum_value: 123 },
    CodeDef { name: "SETTYPEUSERMARKET", member: "SettypeUserMarket", field_index: 124, enum_value: 124 },
    CodeDef { name: "CHECKSOLDITEMSUSERMARKET", member: "CheckSoldItemsUserMarket", field_index: 125, enum_value: 125 },
    CodeDef { name: "SETGMEMAP", member: "SetGmeMap", field_index: 126, enum_value: 126 },
    CodeDef { name: "SETGMEPOINT", member: "SetGmePoint", field_index: 127, enum_value: 127 },
    CodeDef { name: "SETGMETIME", member: "SetGmetTime", field_index: 128, enum_value: 128 },
    CodeDef { name: "STARTNEWGME", member: "Startnewgme", field_index: 129, enum_value: 129 },
    CodeDef { name: "MOVETOGMEMAP", member: "MoveToGmeMap", field_index: 130, enum_value: 130 },
    CodeDef { name: "FINISHGME", member: "FinishgMe", field_index: 131, enum_value: 131 },
    CodeDef { name: "CONTINUEGME", member: "Continuegme", field_index: 132, enum_value: 132 },
    CodeDef { name: "SETGMEPLAYTIME", member: "SetgmeplayTime", field_index: 133, enum_value: 133 },
    CodeDef { name: "SETGMEPAUSETIME", member: "SetgmepauseTime", field_index: 134, enum_value: 134 },
    CodeDef { name: "SETGMELIMITUSER", member: "SetgmeLimitUser", field_index: 135, enum_value: 135 },
    CodeDef { name: "SETEVENTMAP", member: "SeteventMap", field_index: 136, enum_value: 136 },
    CodeDef { name: "RESETEVENTMAP", member: "ReseteventMap", field_index: 137, enum_value: 137 },
    CodeDef { name: "TESTREFINEPOINTS", member: "TestrefinePoints", field_index: 138, enum_value: 138 },
    CodeDef { name: "RESETREFINEWEAPON", member: "ResetrefineWeapon", field_index: 139, enum_value: 139 },
    CodeDef { name: "TESTREFINEACCESSORIES", member: "Testrefineaccessories", field_index: 140, enum_value: 140 },
    CodeDef { name: "REFINEACCESSORIES", member: "RefineAccessories", field_index: 141, enum_value: 141 },
    CodeDef { name: "APPLYMONMISSION", member: "ApplyMonMission", field_index: 142, enum_value: 142 },
    CodeDef { name: "MAPMOVER", member: "MapMover", field_index: 143, enum_value: 143 },
    CodeDef { name: "ADDSTR", member: "AddStr", field_index: 144, enum_value: 144 },
    CodeDef { name: "SETEVENTDAMAGE", member: "SeteventDamage", field_index: 145, enum_value: 145 },
    CodeDef { name: "FORMATSTR", member: "FormatStr", field_index: 146, enum_value: 146 },
    CodeDef { name: "CLEARPATH", member: "ClearPath", field_index: 147, enum_value: 147 },
    CodeDef { name: "ADDPATH", member: "AddPath", field_index: 148, enum_value: 148 },
    CodeDef { name: "APPLYPATH", member: "ApplyPath", field_index: 149, enum_value: 149 },
    CodeDef { name: "MAPSPELL", member: "MapSpell", field_index: 150, enum_value: 150 },
    CodeDef { name: "GIVEEXP", member: "GiveExp", field_index: 151, enum_value: 151 },
    CodeDef { name: "GROUPMOVE", member: "GroupMove", field_index: 152, enum_value: 152 },
    CodeDef { name: "GIVEEXPMAP", member: "GiveExpMap", field_index: 153, enum_value: 153 },
    CodeDef { name: "APPLYMONEX", member: "ApplyMonex", field_index: 154, enum_value: 154 },
    CodeDef { name: "CLEARNAMELIST", member: "ClearNameList", field_index: 155, enum_value: 155 },
    CodeDef { name: "TINGCASTLEVISITOR", member: "TingCastleVisitor", field_index: 156, enum_value: 156 },
    CodeDef { name: "MAKEHEALZONE", member: "MakeHealZone", field_index: 157, enum_value: 157 },
    CodeDef { name: "MAKEDAMAGEZONE", member: "MakeDamageZone", field_index: 158, enum_value: 158 },
    CodeDef { name: "CLEARZONE", member: "ClearZone", field_index: 159, enum_value: 159 },
    CodeDef { name: "READVALUESQL", member: "ReadValueSql", field_index: 160, enum_value: 160 },
    CodeDef { name: "READSTRINGSQL", member: "ReadStringSql", field_index: 161, enum_value: 161 },
    CodeDef { name: "WRITEVALUESQL", member: "WriteValueSql", field_index: 162, enum_value: 162 },
    CodeDef { name: "INCVALUESQL", member: "IncValueSql", field_index: 163, enum_value: 163 },
    CodeDef { name: "DECVALUESQL", member: "DecValueSql", field_index: 164, enum_value: 164 },
    CodeDef { name: "UPDATEVALUESQL", member: "UpDateValueSql", field_index: 165, enum_value: 165 },
    CodeDef { name: "KILLSLAVE", member: "KillSlave", field_index: 166, enum_value: 166 },
    CodeDef { name: "SETITEMEVENT", member: "SetItemEvent", field_index: 167, enum_value: 167 },
    CodeDef { name: "REMOVEITEMEVENT", member: "ReMoveItemEvent", field_index: 168, enum_value: 168 },
    CodeDef { name: "RETURN", member: "Return", field_index: 169, enum_value: 169 },
    CodeDef { name: "CLEARCASTLEOWNER", member: "ClearCastleOwner", field_index: 170, enum_value: 170 },
    CodeDef { name: "DISSOLUTIONGUILD", member: "DissolutionGuild", field_index: 171, enum_value: 171 },
    CodeDef { name: "CHANGEGENDER", member: "ChangeGender", field_index: 172, enum_value: 172 },
    CodeDef { name: "SETFAME", member: "SetFame", field_index: 173, enum_value: 173 },
    CodeDef { name: "CHANGELEVEL", member: "ChangeLevel", field_index: 174, enum_value: 174 },
    CodeDef { name: "MARRY", member: "Marry", field_index: 175, enum_value: 175 },
    CodeDef { name: "UNMARRY", member: "UnMarry", field_index: 176, enum_value: 176 },
    CodeDef { name: "GETMARRY", member: "GetMarry", field_index: 177, enum_value: 177 },
    CodeDef { name: "GETMASTER", member: "GetMaster", field_index: 178, enum_value: 178 },
    CodeDef { name: "CLEARSKILL", member: "ClearSkill", field_index: 179, enum_value: 179 },
    CodeDef { name: "DELNOJOBSKILL", member: "DelnoJobSkill", field_index: 180, enum_value: 180 },
    CodeDef { name: "DELSKILL", member: "DelSkill", field_index: 181, enum_value: 181 },
    CodeDef { name: "ADDSKILL", member: "AddSkill", field_index: 182, enum_value: 182 },
    CodeDef { name: "SKILLLEVEL", member: "SkillLevel", field_index: 183, enum_value: 183 },
    CodeDef { name: "CHANGEPKPOINT", member: "ChangePkPoint", field_index: 184, enum_value: 184 },
    CodeDef { name: "CHANGEEXP", member: "ChangeExp", field_index: 185, enum_value: 185 },
    CodeDef { name: "CHANGEJOB", member: "ChangeJob", field_index: 186, enum_value: 186 },
    CodeDef { name: "MISSION", member: "Mission", field_index: 187, enum_value: 187 },
    CodeDef { name: "MOBPLACE", member: "MobPlace", field_index: 188, enum_value: 188 },
    CodeDef { name: "SETMEMBERTYPE", member: "SetMemberType", field_index: 189, enum_value: 189 },
    CodeDef { name: "SETMEMBERLEVEL", member: "SetMemberLevel", field_index: 190, enum_value: 190 },
    CodeDef { name: "GAMEGOLD", member: "GameGold", field_index: 191, enum_value: 191 },
    CodeDef { name: "AUTOADDGAMEGOLD", member: "AutoAddGameGold", field_index: 192, enum_value: 192 },
    CodeDef { name: "AUTOSUBGAMEGOLD", member: "AutoSubGameGold", field_index: 193, enum_value: 193 },
    CodeDef { name: "CHANGENAMECOLOR", member: "ChangeNameColor", field_index: 194, enum_value: 194 },
    CodeDef { name: "CLEARPASSWORD", member: "ClearPassword", field_index: 195, enum_value: 195 },
    CodeDef { name: "RENEWLEVEL", member: "Renewlevel", field_index: 196, enum_value: 196 },
    CodeDef { name: "KILLMONEXPRATE", member: "KillMonExpRate", field_index: 197, enum_value: 197 },
    CodeDef { name: "POWERRATE", member: "PowerRate", field_index: 198, enum_value: 198 },
    CodeDef { name: "CHANGEPERMISSION", member: "ChangePerMission", field_index: 199, enum_value: 199 },
    CodeDef { name: "KILL", member: "Kill", field_index: 200, enum_value: 200 },
    CodeDef { name: "KICK", member: "Kick", field_index: 201, enum_value: 201 },
    CodeDef { name: "BONUSPOINT", member: "BonusPoint", field_index: 202, enum_value: 202 },
    CodeDef { name: "RESTRENEWLEVEL", member: "Restrenewlevel", field_index: 203, enum_value: 203 },
    CodeDef { name: "DELMARRY", member: "DelMarry", field_index: 204, enum_value: 204 },
    CodeDef { name: "DELMASTER", member: "DelMaster", field_index: 205, enum_value: 205 },
    CodeDef { name: "MASTER", member: "Master", field_index: 206, enum_value: 206 },
    CodeDef { name: "UNMASTER", member: "UnMaster", field_index: 207, enum_value: 207 },
    CodeDef { name: "CREDITPOINT", member: "CreditPoint", field_index: 208, enum_value: 208 },
    CodeDef { name: "CLEARNEEDITEMS", member: "ClearNeedItems", field_index: 209, enum_value: 209 },
    CodeDef { name: "CLEARMAKEITEMS", member: "ClearMakeItems", field_index: 210, enum_value: 210 },
    CodeDef { name: "SETSENDMSGFLAG", member: "SetSendMsgFlag", field_index: 211, enum_value: 211 },
    CodeDef { name: "UPGRADEITEM", member: "UpgradeItems", field_index: 212, enum_value: 212 },
    CodeDef { name: "UPGRADEITEMEX", member: "UpgradeItemSex", field_index: 213, enum_value: 213 },
    CodeDef { name: "MONGENEX", member: "MonGenex", field_index: 214, enum_value: 214 },
    CodeDef { name: "CLEARMAPMON", member: "ClearMapMon", field_index: 215, enum_value: 215 },
    CodeDef { name: "SETMPAMODE", member: "SetMapMode", field_index: 216, enum_value: 216 },
    CodeDef { name: "GAMEPOINT", member: "GamePoint", field_index: 217, enum_value: 217 },
    CodeDef { name: "PKZONE", member: "PvpZone", field_index: 218, enum_value: 218 },
    CodeDef { name: "RESTBONUSPOINT", member: "RestBonusPoint", field_index: 219, enum_value: 219 },
    CodeDef { name: "TAKECASTLEGOLD", member: "TakeCastleGold", field_index: 220, enum_value: 220 },
    CodeDef { name: "HUMANHP", member: "HumanHp", field_index: 221, enum_value: 221 },
    CodeDef { name: "HUMANMP", member: "HumanMp", field_index: 222, enum_value: 222 },
    CodeDef { name: "GUILDBUILDPOINT", member: "BuildPoint", field_index: 223, enum_value: 223 },
    CodeDef { name: "GUILDAURAEPOINT", member: "AuraePoint", field_index: 224, enum_value: 224 },
    CodeDef { name: "GUILDSTABILITYPOINT", member: "StabilityPoint", field_index: 225, enum_value: 225 },
    CodeDef { name: "GUILDFLOURISHPOINT", member: "FlourishPoint", field_index: 226, enum_value: 226 },
    CodeDef { name: "OPENITEMBOX", member: "OpenMagicbox", field_index: 227, enum_value: 227 },
    CodeDef { name: "SETRANKLEVELNAME", member: "SetRankLevelName", field_index: 228, enum_value: 228 },
    CodeDef { name: "GMEXECUTE", member: "GmExecute", field_index: 229, enum_value: 229 },
    CodeDef { name: "GUILDCHIEFITEMCOUNT", member: "GuildChiefItemCount", field_index: 230, enum_value: 230 },
    CodeDef { name: "ADDNAMEDATELIST", member: "AddNameDateList", field_index: 231, enum_value: 231 },
    CodeDef { name: "DELNAMEDATELIST", member: "DelNameDateList", field_index: 232, enum_value: 232 },
    CodeDef { name: "MOBFIREBURN", member: "MobFireburn", field_index: 233, enum_value: 233 },
    CodeDef { name: "MESSAGEBOX", member: "MessageBox", field_index: 234, enum_value: 234 },
    CodeDef { name: "SETSCRIPTFLAG", member: "SetscriptFlag", field_index: 235, enum_value: 235 },
    CodeDef { name: "SETAUTOGETEXP", member: "SetautogetExp", field_index: 236, enum_value: 236 },
    CodeDef { name: "VAR", member: "Var", field_index: 237, enum_value: 237 },
    CodeDef { name: "LOADVAR", member: "LoadVar", field_index: 238, enum_value: 238 },
    CodeDef { name: "SAVEVAR", member: "SaveVar", field_index: 239, enum_value: 239 },
    CodeDef { name: "CALCVAR", member: "CalcVar", field_index: 240, enum_value: 240 },
    CodeDef { name: "OFFLINEPLAY", member: "OffLinePlay", field_index: 241, enum_value: 241 },
    CodeDef { name: "KICKOFFLINE", member: "KickOffline", field_index: 242, enum_value: 242 },
    CodeDef { name: "STARTTAKEGOLD", member: "StarttakeGold", field_index: 243, enum_value: 243 },
    CodeDef { name: "CLEARDELAYGOTO", member: "ClearDelayGoto", field_index: 244, enum_value: 244 },
    CodeDef { name: "CHANGERECOMMENDGAMEGOLD", member: "ChangereCommendGameGold", field_index: 245, enum_value: 245 },
    CodeDef { name: "ANSIREPLACETEXT", member: "AnsirePlaceText", field_index: 246, enum_value: 246 },
    CodeDef { name: "ENCODETEXT", member: "EncodeText", field_index: 247, enum_value: 247 },
    CodeDef { name: "DECODETEXT", member: "DecodeText", field_index: 248, enum_value: 248 },
    CodeDef { name: "ADDTEXTLIST", member: "AddTextList", field_index: 249, enum_value: 249 },
    CodeDef { name: "DELTEXTLIST", member: "DelTextList", field_index: 250, enum_value: 250 },
    CodeDef { name: "GROUPMAPMOVE", member: "GroupMapMove", field_index: 251, enum_value: 251 },
    CodeDef { name: "RECALLHUMAN", member: "ReCallHuman", field_index: 252, enum_value: 252 },
    CodeDef { name: "REGOTO", member: "Regoto", field_index: 253, enum_value: 253 },
    CodeDef { name: "INTTOSTR", member: "IntToStr", field_index: 254, enum_value: 254 },
    CodeDef { name: "STRTOINT", member: "StrToInt", field_index: 255, enum_value: 255 },
    CodeDef { name: "GUILDMOVE", member: "GuildMove", field_index: 256, enum_value: 256 },
    CodeDef { name: "GUILDMAPMOVE", member: "GuildMapMove", field_index: 257, enum_value: 257 },
    CodeDef { name: "RANDOMMOVE", member: "RandomMove", field_index: 258, enum_value: 258 },
    CodeDef { name: "USEBONUSPOINT", member: "UseBonusPoint", field_index: 259, enum_value: 259 },
    CodeDef { name: "TAKEONITEM", member: "TakeOnItem", field_index: 260, enum_value: 260 },
    CodeDef { name: "TAKEOFFITEM", member: "TakeOffItem", field_index: 261, enum_value: 261 },
    CodeDef { name: "GIVEEX", member: "GiveEx", field_index: 262, enum_value: 262 },
    CodeDef { name: "TIMEOPEN", member: "TimeOpen", field_index: 263, enum_value: 263 },
    CodeDef { name: "TIMECLOSE", member: "TimeClose", field_index: 264, enum_value: 264 },
    CodeDef { name: "GUILDMEMBERMAXLIMIT", member: "GuildMemberMaxLimit", field_index: 265, enum_value: 265 },
    CodeDef { name: "ADDGUILDNAMEDATELIST", member: "AddGuildNamedateList", field_index: 266, enum_value: 266 },
    CodeDef { name: "DELGUILDNAMEDATELIST", member: "DelGuildNamedateList", field_index: 267, enum_value: 267 },
    CodeDef { name: "GOHOME", member: "GoHome", field_index: 268, enum_value: 268 },
    CodeDef { name: "ADDBLOCKIPLIST", member: "AddBlockIpList", field_index: 269, enum_value: 269 },
    CodeDef { name: "MOVEDATA", member: "MovData", field_index: 270, enum_value: 270 },
    CodeDef { name: "SENDCOLORMSG", member: "SendColorMsg", field_index: 271, enum_value: 271 },
    CodeDef { name: "ADDRANDOMMAPGATE", member: "AddRandomMapGate", field_index: 272, enum_value: 272 },
    CodeDef { name: "DELRANDOMMAPGATE", member: "DelRandomMapGate", field_index: 273, enum_value: 273 },
    CodeDef { name: "GETRANDOMMAPGATE", member: "GetRandommApGate", field_index: 274, enum_value: 274 },
    CodeDef { name: "OPENBOOK", member: "OpenBook", field_index: 275, enum_value: 275 },
    CodeDef { name: "OPENBOX", member: "OpenBox", field_index: 276, enum_value: 276 },
    CodeDef { name: "CHANGEITEMS", member: "ChangeItems", field_index: 277, enum_value: 277 },
    CodeDef { name: "CLEARREMEMBER", member: "ClearreMember", field_index: 278, enum_value: 278 },
    CodeDef { name: "SENDMOVEMSG", member: "SendMoveMsg", field_index: 279, enum_value: 279 },
    CodeDef { name: "SETITEMSLIGHT", member: "SetItemsLight", field_index: 280, enum_value: 280 },
    CodeDef { name: "READRANDOMSTR", member: "ReadrandomStr", field_index: 281, enum_value: 281 },
    CodeDef { name: "CHANGERANGEMONPOS", member: "ChangeRangeMonPos", field_index: 282, enum_value: 282 },
    CodeDef { name: "READ", member: "Read", field_index: 283, enum_value: 283 },
    CodeDef { name: "WRITE", member: "Write", field_index: 284, enum_value: 284 },
    CodeDef { name: "CHANGEITEMNEWADDVALUE", member: "ChangeItemNewAddValue", field_index: 285, enum_value: 285 },
    CodeDef { name: "OPENHOMEPAGE", member: "OpenHomePage", field_index: 286, enum_value: 286 },
    CodeDef { name: "PKZONEX", member: "PvpZoneEx", field_index: 287, enum_value: 287 },
    CodeDef { name: "SETITEMSLIGHTEX", member: "SetItemslightex", field_index: 288, enum_value: 288 },
    CodeDef { name: "SPELL", member: "Spell", field_index: 289, enum_value: 289 },
    CodeDef { name: "ADDMAPMAGICEVENT", member: "AddMapMagicEvent", field_index: 290, enum_value: 290 },
    CodeDef { name: "RANDOMADDMAPMAGICEVENT", member: "RandomAddMapMagicEvent", field_index: 291, enum_value: 291 },
    CodeDef { name: "SNOW", member: "SNow", field_index: 292, enum_value: 292 },
    CodeDef { name: "RANDOMUPGRADEITEM", member: "RandoMupgradeItem", field_index: 293, enum_value: 293 },
    CodeDef { name: "LOCK", member: "Lock", field_index: 294, enum_value: 294 },
    CodeDef { name: "UNLOCK", member: "Unlock", field_index: 295, enum_value: 295 },
    CodeDef { name: "GETDUELITEMS", member: "GetdUelItems", field_index: 296, enum_value: 296 },
    CodeDef { name: "CANUSEITEM", member: "CanUseItem", field_index: 297, enum_value: 297 },
    CodeDef { name: "AUTOGOTOXY", member: "AutoGotoxy", field_index: 298, enum_value: 298 },
    CodeDef { name: "CHANGENEWSTATUS", member: "ChangeNewStatus", field_index: 299, enum_value: 299 },
    CodeDef { name: "SENDDELAYMSG", member: "SendDelayMsg", field_index: 300, enum_value: 300 },
    CodeDef { name: "ACTVARLIST", member: "ActvarList", field_index: 301, enum_value: 301 },
    CodeDef { name: "SETMASKED", member: "SetMasked", field_index: 302, enum_value: 302 },
    CodeDef { name: "SENDCENTERMSG", member: "SendCenterMsg", field_index: 303, enum_value: 303 },
    CodeDef { name: "CHANGEUSEITEMSTARSLEVEL", member: "ChangeUseItemStarsLevel", field_index: 304, enum_value: 304 },
    CodeDef { name: "CHANGEBAGITEMSTARSLEVEL", member: "ChangeBagItemStarsLevel", field_index: 305, enum_value: 305 },
    CodeDef { name: "BINDBAGITEM", member: "BindbagItem", field_index: 306, enum_value: 306 },
    CodeDef { name: "SETONTIMER", member: "SetOnTimer", field_index: 307, enum_value: 307 },
    CodeDef { name: "SETOFFTIMER", member: "KillScTimer", field_index: 308, enum_value: 308 },
    CodeDef { name: "PLAYSOUND", member: "PlaySound", field_index: 309, enum_value: 309 },
    CodeDef { name: "SHOWEFFECT", member: "ShowEffect", field_index: 310, enum_value: 310 },
    CodeDef { name: "CHANGEITEMVALUE", member: "ChangeItemvalue", field_index: 311, enum_value: 311 },
    CodeDef { name: "VIBRATION", member: "Vibration", field_index: 312, enum_value: 312 },
    CodeDef { name: "OPENBIGDIALOGBOX", member: "OpenbigDialogBox", field_index: 313, enum_value: 313 },
    CodeDef { name: "CLOSEBIGDIALOGBOX", member: "CloseBigDialogBox", field_index: 314, enum_value: 314 },
    CodeDef { name: "TAGMAPMOVE", member: "TagMapMove", field_index: 315, enum_value: 315 },
    CodeDef { name: "TAGMAPINFO", member: "TagMapinfo", field_index: 316, enum_value: 316 },
    CodeDef { name: "AISTART", member: "AiStart", field_index: 317, enum_value: 317 },
    CodeDef { name: "AISTOP", member: "AiStop", field_index: 318, enum_value: 318 },
    CodeDef { name: "CHANGEIPADDRESS", member: "ChangeIpAddress", field_index: 319, enum_value: 319 },
    CodeDef { name: "CHANGEATTATCKMODE", member: "ChangeAttatckMode", field_index: 320, enum_value: 320 },
    CodeDef { name: "AILOGON", member: "AiLogon", field_index: 321, enum_value: 321 },
    CodeDef { name: "AILOGONEX", member: "AiLogonEx", field_index: 322, enum_value: 322 },
    CodeDef { name: "KICKALL", member: "KickAll", field_index: 323, enum_value: 323 },
    CodeDef { name: "TAKEITEMLIST", member: "TakeItemList", field_index: 324, enum_value: 324 },
    CodeDef { name: "SHOWRANKLEVLNAME", member: "ShowRankLevlName", field_index: 325, enum_value: 325 },
    CodeDef { name: "LOADROBOTCONFIG", member: "LoadRobotConfig", field_index: 326, enum_value: 326 },
    CodeDef { name: "ACTMISSION", member: "ActMission", field_index: 327, enum_value: 327 },
    CodeDef { name: "GUILDRECALL", member: "GuildReCall", field_index: 328, enum_value: 328 },
    CodeDef { name: "GROUPADDLIST", member: "GroupAddList", field_index: 329, enum_value: 329 },
    CodeDef { name: "CLEARLIST", member: "ClearList", field_index: 330, enum_value: 330 },
    CodeDef { name: "GROUPRECALL", member: "GroupReCall", field_index: 331, enum_value: 331 },
    CodeDef { name: "GROUPMOVEMAP", member: "GroupMoveMap", field_index: 332, enum_value: 332 },
    CodeDef { name: "SAVESLAVES", member: "SaveSlaves", field_index: 333, enum_value: 333 },
    CodeDef { name: "CHECKUSERDATE", member: "CheckUserDate", field_index: 334, enum_value: 334 },
    CodeDef { name: "ADDUSERDATE", member: "AddUserDate", field_index: 335, enum_value: 335 },
    CodeDef { name: "DELUSERDATE", member: "DelUserDate", field_index: 336, enum_value: 336 },
    CodeDef { name: "OFFLINE", member: "OffLine", field_index: 337, enum_value: 337 },
    CodeDef { name: "REPAIRALL", member: "RepairAll", field_index: 338, enum_value: 338 },
    CodeDef { name: "SETRANDOMNO", member: "SetRandomNo", field_index: 339, enum_value: 339 },
    CodeDef { name: "QUERYBAGITEMS", member: "QueryBagItems", field_index: 340, enum_value: 340 },
    CodeDef { name: "THROWITEM", member: "ThrowItem", field_index: 341, enum_value: 341 },
    CodeDef { name: "OPENYBDEAL", member: "OpenYbDeal", field_index: 342, enum_value: 342 },
    CodeDef { name: "QUERYYBSELL", member: "QueryYbSell", field_index: 343, enum_value: 343 },
    CodeDef { name: "QUERYYBDEAL", member: "QueryYbDeal", field_index: 344, enum_value: 344 },
    CodeDef { name: "DELAYGOTO", member: "DelayGoto", field_index: 345, enum_value: 345 },
    CodeDef { name: "DELAYCALL", member: "DelayCall", field_index: 346, enum_value: 346 },
    CodeDef { name: "QUERYVALUE", member: "QueryValue", field_index: 347, enum_value: 347 },
    CodeDef { name: "KILLSLAVENAME", member: "KillSlaveName", field_index: 348, enum_value: 348 },
    CodeDef { name: "QUERYITEMDLG", member: "QueryItemDlg", field_index: 349, enum_value: 349 },
    CodeDef { name: "UPGRADEDLGITEM", member: "UpgradeDlgItem", field_index: 350, enum_value: 350 },
    CodeDef { name: "GETDLGITEMVALUE", member: "GetDlgItemValue", field_index: 351, enum_value: 351 },
    CodeDef { name: "TAKEDLGITEM", member: "TakeDlgItem", field_index: 352, enum_value: 352 },
];

/// GrobalVarCode 的 sVAR_/tVAR_ 配对表：(脚本变量名, 替换文本)。
#[rustfmt::skip]
pub static GROBAL_VAR_PAIRS: &[(&str, &str)] = &[
    ("$SERVERNAME", "<$1>"),
    ("$SERVERIP", "<$2>"),
    ("$WEBSITE", "<$3>"),
    ("$BBSSITE", "<$4>"),
    ("$CLIENTDOWNLOAD", "<$5>"),
    ("$QQ", "<$6>"),
    ("$PHONE", "<$7>"),
    ("$BANKACCOUNT0", "<$8>"),
    ("$BANKACCOUNT1", "<$9>"),
    ("$BANKACCOUNT2", "<$10>"),
    ("$BANKACCOUNT3", "<$11>"),
    ("$BANKACCOUNT4", "<$12>"),
    ("$BANKACCOUNT5", "<$13>"),
    ("$BANKACCOUNT6", "<$14>"),
    ("$BANKACCOUNT7", "<$15>"),
    ("$BANKACCOUNT8", "<$16>"),
    ("$BANKACCOUNT9", "<$17>"),
    ("$GAMEGOLDNAME", "<$18>"),
    ("$GAMEPOINTNAME", "<$19>"),
    ("$USERCOUNT", "<$20>"),
    ("$DATETIME", "<$21>"),
    ("$USERNAME", "<$22>"),
    ("$MAPNAME", "<$23>"),
    ("$GUILDNAME", "<$24>"),
    ("$RANKNAME", "<$25>"),
    ("$LEVEL", "<$26>"),
    ("$HP", "<$27>"),
    ("$MAXHP", "<$28>"),
    ("$MP", "<$29>"),
    ("$MAXMP", "<$30>"),
    ("$AC", "<$31>"),
    ("$MAXAC", "<$32>"),
    ("$MAC", "<$33>"),
    ("$MAXMAC", "<$34>"),
    ("$DC", "<$35>"),
    ("$MAXDC", "<$36>"),
    ("$MC", "<$37>"),
    ("$MAXMC", "<$38>"),
    ("$SC", "<$39>"),
    ("$MAXSC", "<$40>"),
    ("$EXP", "<$41>"),
    ("$MAXEXP", "<$42>"),
    ("$PKPOINT", "<$43>"),
    ("$CREDITPOINT", "<$44>"),
    ("$GOLDCOUNT", "<$45>"),
    ("$GAMEGOLD", "<$46>"),
    ("$GAMEPOINT", "<$47>"),
    ("$LOGINTIME", "<$48>"),
    ("$LOGINLONG", "<$49>"),
    ("$DRESS", "<$50>"),
    ("$WEAPON", "<$51>"),
    ("$RIGHTHAND", "<$52>"),
    ("$HELMET", "<$53>"),
    ("$NECKLACE", "<$54>"),
    ("$RING_R", "<$55>"),
    ("$RING_L", "<$56>"),
    ("$ARMRING_R", "<$57>"),
    ("$ARMRING_L", "<$58>"),
    ("$BUJUK", "<$59>"),
    ("$BELT", "<$60>"),
    ("$BOOTS", "<$61>"),
    ("$CHARM", "<$62>"),
    ("$HOUSE", "<$63>"),
    ("$CIMELIA", "<$64>"),
    ("$IPADDR", "<$65>"),
    ("$IPLOCAL", "<$66>"),
    ("$GUILDBUILDPOINT", "<$67>"),
    ("$GUILDAURAEPOINT", "<$68>"),
    ("$GUILDSTABILITYPOINT", "<$69>"),
    ("$GUILDFLOURISHPOINT", "<$70>"),
    ("$GUILDMONEYCOUNT", "<$71>"),
    ("$REQUESTCASTLEWARITEM", "<$72>"),
    ("$REQUESTCASTLEWARDAY", "<$73>"),
    ("$REQUESTBUILDGUILDITEM", "<$74>"),
    ("$OWNERGUILD", "<$75>"),
    ("$CASTLENAME", "<$76>"),
    ("$LORD", "<$77>"),
    ("$GUILDWARFEE", "<$78>"),
    ("$BUILDGUILDFEE", "<$79>"),
    ("$CASTLEWARDATE", "<$80>"),
    ("$LISTOFWAR", "<$81>"),
    ("$CASTLECHANGEDATE", "<$82>"),
    ("$CASTLEWARLASTDATE", "<$83>"),
    ("$CASTLEGETDAYS", "<$84>"),
    ("$CMD_DATE", "<$85>"),
    ("$CMD_PRVMSG", "<$86>"),
    ("$CMD_ALLOWMSG", "<$87>"),
    ("$CMD_LETSHOUT", "<$88>"),
    ("$CMD_LETTRADE", "<$89>"),
    ("$CMD_LETGuild", "<$90>"),
    ("$CMD_ENDGUILD", "<$91>"),
    ("$CMD_BANGUILDCHAT", "<$92>"),
    ("$CMD_AUTHALLY", "<$93>"),
    ("$CMD_AUTH", "<$94>"),
    ("$CMD_AUTHCANCEL", "<$95>"),
    ("$CMD_USERMOVE", "<$96>"),
    ("$CMD_SEARCHING", "<$97>"),
    ("$CMD_ALLOWGROUPCALL", "<$98>"),
    ("$CMD_GROUPRECALLL", "<$99>"),
    ("$CMD_ALLOWGUILDRECALL", "<$100>"),
    ("$CMD_GUILDRECALLL", "<$101>"),
    ("$CMD_DEAR", "<$102>"),
    ("$CMD_ALLOWDEARRCALL", "<$103>"),
    ("$CMD_DEARRECALL", "<$104>"),
    ("$CMD_MASTER", "<$105>"),
    ("$CMD_ALLOWMASTERRECALL", "<$106>"),
    ("$CMD_MASTERECALL", "<$107>"),
    ("$CMD_TAKEONHORSE", "<$108>"),
    ("$CMD_TAKEOFHORSE", "<$109>"),
    ("$CMD_ALLSYSMSG", "<$110>"),
    ("$CMD_MEMBERFUNCTION", "<$111>"),
    ("$CMD_MEMBERFUNCTIONEX", "<$112>"),
    ("$CASTLEGOLD", "<$113>"),
    ("$TODAYINCOME", "<$114>"),
    ("$CASTLEDOORSTATE", "<$115>"),
    ("$REPAIRDOORGOLD", "<$116>"),
    ("$REPAIRWALLGOLD", "<$117>"),
    ("$GUARDFEE", "<$118>"),
    ("$ARCHERFEE", "<$119>"),
    ("$GUARDRULE", "<$120>"),
    ("$HUMAN(", "<$122/{0}>"),
    ("$GUILD(", "<$123/{0}>"),
    ("$GLOBAL(", "<$124/{0}>"),
    ("$STR(", "<$125/{0}>"),
    ("$STORAGE2STATE", "<$126>"),
    ("$STORAGE3STATE", "<$127>"),
    ("$STORAGE4STATE", "<$128>"),
    ("$STORAGE5STATE", "<$129>"),
    ("$SELFNAME", "<$130>"),
    ("$POSENAME", "<$131>"),
    ("$GAMEDIAMOND", "<$132>"),
    ("$GAMEGIRD", "<$133>"),
    ("$MISSIONARITHMOMETER(", "<$134/{0}>"),
    ("$CMD_ALLOWFIREND", "<$135>"),
    ("$EFFIGYSTATE", "<$136>"),
    ("$EFFIGYOFFSET", "<$137>"),
    ("$YEAR", "<$138>"),
    ("$MONTH", "<$139>"),
    ("$DAY", "<$140>"),
    ("$HOUR", "<$141>"),
    ("$MINUTE", "<$142>"),
    ("$SEC", "<$143>"),
    ("$MAP", "<$144>"),
    ("$X", "<$145>"),
    ("$Y", "<$146>"),
    ("$UNMASTER_FORCE", "<$147>"),
    ("$TEAM", "<$148/{0}>"),
    ("$USERGOLDCOUNT", "<$149>"),
    ("$MAXGOLDCOUNT", "<$150>"),
    ("$STORAGEGOLDCOUNT", "<$151>"),
    ("$BINDGOLDCOUNT", "<$152>"),
    ("$UPGRADEWEAPONFEE", "<$153>"),
    ("$USERWEAPON", "<$154>"),
    ("$CMD_STARTQUEST", "<$155>"),
    ("$FBMAPNAME", "<$156>"),
    ("$FBMAP", "<$157>"),
    ("$ACCOUNT", "<$158>"),
    ("$ASSEMBLEITEMNAME", "<$159>"),
];
// GROBAL_VAR_PAIRS 条数（对账用）：158
